name: Update Site Content

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

# Add permissions for the workflow
permissions:
  contents: write  # This allows the workflow to push changes

jobs:
  update-content:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    
    - name: Create directories
      run: |
        mkdir -p portfolio get-in-touch thank-you hapsy skenero-cz rootie mythamin
    
    - name: Create GTM tags file
      run: |
        printf "<!-- Google Tag Manager -->\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\nnew Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,'script','dataLayer','GTM-MBQVSR5F');</script>\n<!-- End Google Tag Manager -->" > gtm-head.txt
        printf "<!-- Google Tag Manager (noscript) -->\n<noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-MBQVSR5F\"\nheight=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>\n<!-- End Google Tag Manager (noscript) -->" > gtm-body.txt
    
    - name: Create Clarity tracking code
      run: |
        printf "<!-- Clarity tracking code -->\n<script type=\"text/javascript\">\n    (function(c,l,a,r,i,t,y){\n        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};\n        t=l.createElement(r);t.async=1;t.src=\"https://www.clarity.ms/tag/\"+i;\n        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);\n    })(window, document, \"clarity\", \"script\", \"r8bd1fgcsz\");\n</script>\n<!-- End Clarity tracking code -->" > clarity.txt
    
    - name: Download and process index page
      run: |
        curl -s "https://tech.nocodexport.com/download?site=ohnysko.framer.ai" > temp.html
        awk '/<head>/{print;system("cat gtm-head.txt");system("cat clarity.txt");next} /<body>/{print;system("cat gtm-body.txt");next} {print}' temp.html > index.html
    
    - name: Download and process portfolio page
      run: |
        curl -s "https://tech.nocodexport.com/download?site=ohnysko.framer.ai/portfolio" > temp.html
        awk '/<head>/{print;system("cat gtm-head.txt");system("cat clarity.txt");next} /<body>/{print;system("cat gtm-body.txt");next} {print}' temp.html > portfolio/index.html
    
    - name: Download and process get-in-touch page
      run: |
        curl -s "https://tech.nocodexport.com/download?site=ohnysko.framer.ai/get-in-touch" > temp.html
        awk '/<head>/{print;system("cat gtm-head.txt");system("cat clarity.txt");next} /<body>/{print;system("cat gtm-body.txt");next} {print}' temp.html > get-in-touch/index.html
    
    - name: Download and process thank-you page
      run: |
        curl -s "https://tech.nocodexport.com/download?site=ohnysko.framer.ai/thank-you" > temp.html
        awk '/<head>/{print;system("cat gtm-head.txt");system("cat clarity.txt");next} /<body>/{print;system("cat gtm-body.txt");next} {print}' temp.html > thank-you/index.html
    
    - name: Download and process hapsy page
      run: |
        curl -s "https://tech.nocodexport.com/download?site=ohnysko.framer.ai/hapsy" > temp.html
        awk '/<head>/{print;system("cat gtm-head.txt");system("cat clarity.txt");next} /<body>/{print;system("cat gtm-body.txt");next} {print}' temp.html > hapsy/index.html
    
    - name: Download and process skenero-cz page
      run: |
        curl -s "https://tech.nocodexport.com/download?site=ohnysko.framer.ai/skenero-cz" > temp.html
        awk '/<head>/{print;system("cat gtm-head.txt");system("cat clarity.txt");next} /<body>/{print;system("cat gtm-body.txt");next} {print}' temp.html > skenero-cz/index.html
    
    - name: Download and process rootie page
      run: |
        curl -s "https://tech.nocodexport.com/download?site=ohnysko.framer.ai/rootie" > temp.html
        awk '/<head>/{print;system("cat gtm-head.txt");system("cat clarity.txt");next} /<body>/{print;system("cat gtm-body.txt");next} {print}' temp.html > rootie/index.html
    
    - name: Download and process mythamin page
      run: |
        curl -s "https://tech.nocodexport.com/download?site=ohnysko.framer.ai/mythamin" > temp.html
        awk '/<head>/{print;system("cat gtm-head.txt");system("cat clarity.txt");next} /<body>/{print;system("cat gtm-body.txt");next} {print}' temp.html > mythamin/index.html

    - name: Download and process 404 page
      run: |
        curl -s "https://tech.nocodexport.com/download?site=ohnysko.framer.ai/404" > temp.html
        awk '/<head>/{print;system("cat gtm-head.txt");system("cat clarity.txt");next} /<body>/{print;system("cat gtm-body.txt");next} {print}' temp.html > 404.html
    
    - name: Clean up temporary files
      run: |
        rm temp.html gtm-head.txt gtm-body.txt clarity.txt
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html portfolio/index.html get-in-touch/index.html thank-you/index.html hapsy/index.html skenero-cz/index.html rootie/index.html mythamin/index.html 404.html
        git commit -m "Update site content with GTM and Clarity tracking"
        git push